version: '3.8'

services:
  api:
    image: rodcordeiro/chat:latest
    container_name: chat_api
    depends_on:
      - chat_db
    restart: always
    ports:
      - '3340:80'
    env_file:
      - .env
    networks:
      - chat

networks:
  chat:
    driver: bridge