version: '3.8'

services:
  chat_db:
    image: mysql:latest
    container_name: chat_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    ports:
      - "3335:3306"
    expose:
      # Opens port 3306 on the container
      - "3335"
    networks:
      - chat
    volumes:
      - "/chat"

  api:
    image: rodcordeiro/chat:latest
    container_name: chat_api
    depends_on:
      - chat_db
    restart: always
    ports:
      - '3333:80'
    env_file:
      - .env
    networks:
      - chat

networks:
  chat:
    driver: bridge